[package]
name = "dler-kun"
version = "0.1.0"
description = "dler-kun desktop app"
authors = ["nezumi0627"]
license = "MIT"
repository = "https://github.com/nezumi0627/dler-kun"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
